### ISSUE TITLE
Adding a status indicator for certain system services

### ISSUE THREAD

**Issue by spiral6** [ColinWaddell/CurrantPi#43]
Hello, I have a feature request! I would like to have a services section to see if certain system services in through SystemD on the host machine are running, indicated by RED if not running and GREEN if running.

Typically a simple shell command would work, `service status something` would return a status code for `something.service`. I assume you can query certain shell commands in PHP judging by the other statistics. However I have no experience in PHP development, but maybe able to assist by learning it, and thus may do a pull request later. The server would update the status every 5 minutes or so, and also has a manual refresh button to check the status, and then update the webpage so.

**Comment by ColinWaddell** [comment]
Hey. This is a cool idea. I've got a few thoughts on how you could best do
it, shouldn't be too tricky.

Once I'm back from holiday I'll pop some thoughts in this thread for you.

On 3 Jan 2017 8:37 p.m., "Shamee Mahmud" <notifications@github.com> wrote:

Hello, I have a feature request! I would like to have a services section to
see if certain system services in through SystemD on the host machine are
running, indicated by RED if not running and GREEN if running.

Typically a simple shell command would work, service status something would
return a status code for something.service. I assume you can query certain
shell commands in PHP judging by the other statistics. However I have no
experience in PHP development, but maybe able to assist by learning it, and
thus may do a pull request later. The server would update the status every
5 minutes or so, and also has a manual refresh button to check the status,
and then update the webpage so.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ColinWaddell/CurrantPi/issues/43>, or mute the thread

**Comment by ColinWaddell** [comment]
Hey @spiral6 

Don't know if you remember this feature request. I finally remembered to getting around to have a go at it. If you checkout the branch ```services``` you can have a shot. 

My only beef with my implementation is that it really slows down the loading of the page - it takes ages to get the services list.

If you fancy a shot at speeding it up, batter in. I suppose you could start loading it in the background via AJAX but I'm really against touching this project with js.

<img width="654" alt="screen shot 2017-10-19 at 21 21 27" src="https://user-images.githubusercontent.com/1848325/31792331-89cb3f0a-b513-11e7-846f-f3bf7018a190.png">

**Comment by spiral6** [comment]
Alrighty, thank you!
